# Generated by Django 3.0.6 on 2020-06-02 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('production', '0001_initial'),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='shop.Shop'),
        ),
        migrations.AddField(
            model_name='good',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods', to='shop.Shop'),
        ),
        migrations.AddField(
            model_name='good',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goods', to='production.Supplier'),
        ),
        migrations.AlterUniqueTogether(
            name='supplier',
            unique_together={('shop', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='good',
            unique_together={('shop', 'name')},
        ),
    ]
