# Generated by Django 3.0.7 on 2020-06-22 12:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LineChannel',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=31)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('email_address', models.EmailField(blank=True, max_length=254, null=True)),
                ('privacy_policy_url', models.URLField(blank=True, null=True)),
                ('terms_url', models.URLField(blank=True, null=True)),
                ('numeric_id', models.CharField(blank=True, max_length=10, null=True)),
                ('secret', models.CharField(blank=True, max_length=32, null=True)),
                ('assertion_signing_key', models.CharField(blank=True, max_length=40, null=True)),
                ('bot_id', models.CharField(blank=True, max_length=31, null=True)),
                ('access_token', models.CharField(blank=True, max_length=200, null=True)),
                ('creator_user_id', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
