# Generated by Django 3.0.7 on 2020-06-25 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('line_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineChannelMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_following', models.BooleanField(default=False)),
                ('is_promotable', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False, help_text='user is admin or staff for line channel')),
                ('line_channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_channel_memberships', to='line_app.LineChannel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LineUserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=30, null=True)),
                ('language', models.CharField(max_length=8, null=True)),
                ('picture_url', models.URLField(null=True)),
                ('status_message', models.CharField(max_length=550, null=True)),
                ('line_id', models.CharField(max_length=25, null=True)),
                ('line_channels', models.ManyToManyField(blank=True, through='line_app.LineChannelMembership', to='line_app.LineChannel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='linechannelmembership',
            name='line_user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_channel_memberships', to='line_app.LineUserProfile'),
        ),
    ]
