# Generated by Django 3.0.7 on 2020-06-25 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line_app', '0002_auto_20200625_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineuserprofile',
            name='user_id',
            field=models.CharField(max_length=40),
        ),
    ]
