# Generated by Django 3.0.7 on 2020-06-25 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('line_app', '0003_auto_20200625_1120'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lineuserprofile',
            old_name='user_id',
            new_name='line_user_id',
        ),
        migrations.RenameField(
            model_name='lineuserprofile',
            old_name='line_id',
            new_name='line_username_id',
        ),
    ]
