# Generated by Django 3.0.7 on 2020-07-07 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('line_app', '0005_lineuserprofile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineRichMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(default=1)),
                ('line_channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_rich_menus', to='line_app.LineChannel')),
            ],
        ),
    ]
