# Generated by Django 3.0.7 on 2020-07-10 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_auto_20200710_0836'),
        ('line_app', '0006_linerichmenu'),
    ]

    operations = [
        migrations.AddField(
            model_name='linechannel',
            name='admin_channel',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='linechannel',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='line_channel', to='shop.Shop'),
        ),
        migrations.AlterField(
            model_name='linechannel',
            name='numeric_id',
            field=models.CharField(blank=True, help_text='Channel ID at top of basic settings screen', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='linechannel',
            name='secret',
            field=models.CharField(blank=True, help_text='Channel secret on basic settings screen', max_length=32, null=True),
        ),
    ]
