# Generated by Django 3.0.7 on 2020-07-14 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line_app', '0008_auto_20200714_0809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineuserprofile',
            name='language',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='lineuserprofile',
            name='line_username_id',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='lineuserprofile',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='lineuserprofile',
            name='picture_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lineuserprofile',
            name='status_message',
            field=models.CharField(blank=True, max_length=550, null=True),
        ),
    ]
