# Generated by Django 3.0.7 on 2020-07-15 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line_app', '0009_auto_20200714_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='linerichmenu',
            name='line_rich_menu_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
