# Generated by Django 3.0.7 on 2020-07-15 07:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('line_app', '0010_linerichmenu_line_rich_menu_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineuserprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='line_user_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
