# Generated by Django 3.0.7 on 2020-07-18 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line_app', '0011_auto_20200715_0737'),
    ]

    operations = [
        migrations.AddField(
            model_name='linechannel',
            name='direct_link_url',
            field=models.URLField(blank=True, help_text='eg. https://lin.ee/123abc', null=True),
        ),
        migrations.AlterField(
            model_name='linechannel',
            name='bot_id',
            field=models.CharField(blank=True, help_text='eg. @A1b2c3', max_length=31, null=True),
        ),
    ]
