# Generated by Django 3.0.7 on 2020-07-20 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line_app', '0012_auto_20200718_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='linechannel',
            name='channel_type',
            field=models.CharField(choices=[('bot', 'customer messaging API'), ('admin', 'admin messaging API'), ('login', 'LINE Login')], default='bot', max_length=5),
            preserve_default=False,
        ),
    ]
