# Generated by Django 3.0.7 on 2020-07-20 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('line_app', '0013_linechannel_channel_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linechannel',
            name='admin_channel',
        ),
    ]
