# Generated by Django 3.0.7 on 2020-07-20 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_auto_20200718_0819'),
        ('line_app', '0014_remove_linechannel_admin_channel'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='linechannel',
            unique_together={('shop', 'channel_type')},
        ),
    ]
