# Generated by Django 3.0.7 on 2020-07-20 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line_app', '0016_auto_20200720_0828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linerichmenu',
            name='index',
            field=models.SmallIntegerField(choices=[(0, 'main menu')], default=0),
        ),
    ]
