# Generated by Django 3.0.7 on 2020-07-20 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('line_app', '0018_remove_linechannelmembership_current_rich_menu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linerichmenu',
            name='line_channel',
        ),
        migrations.AddField(
            model_name='linerichmenu',
            name='_is_currently_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='linerichmenu',
            name='line_channel_membership',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='line_rich_menus', to='line_app.LineChannelMembership'),
            preserve_default=False,
        ),
    ]
