# Generated by Django 3.0.7 on 2020-07-24 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0028_auto_20200722_0707'),
        ('line_app', '0019_auto_20200720_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linechannel',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='line_channels', to='shop.Shop'),
        ),
    ]
