# Generated by Django 3.0.7 on 2020-06-25 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='unstructured_text_address',
            field=models.TextField(blank=True, default=''),
        ),
    ]
