# Generated by Django 3.0.7 on 2020-08-12 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_unstructured_text_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pushover_key',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
