# Generated by Django 3.0.7 on 2020-08-12 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_pushover_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pushover_device_name',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
    ]
