# Generated by Django 2.1.7 on 2019-05-27 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='show_skibi_credits',
            field=models.BooleanField(default=True),
        ),
    ]
