# Generated by Django 2.1.7 on 2019-05-27 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_show_skibi_credits'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('href', models.URLField()),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='blog.Blog')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
