# Generated by Django 2.1.7 on 2019-05-27 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='title',
            field=models.CharField(default='title', max_length=128),
            preserve_default=False,
        ),
    ]
