# Generated by Django 2.1.7 on 2019-05-27 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_link_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='footer_text',
            field=models.TextField(default=''),
        ),
    ]
