# Generated by Django 2.1.7 on 2019-04-24 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190424_1701'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='sites',
            new_name='site',
        ),
    ]
