# Generated by Django 2.1.7 on 2019-04-24 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190424_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='site',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog', to='sites.Site'),
        ),
    ]
