# Generated by Django 2.1.7 on 2019-04-24 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190424_1704'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('static_dir_name', models.CharField(max_length=100, unique=True)),
                ('license_href', models.URLField()),
                ('js_href', models.URLField()),
                ('css_href', models.URLField()),
                ('live', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='blog',
            name='site',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='blog', to='sites.Site'),
        ),
        migrations.AddField(
            model_name='blog',
            name='theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='blogs', to='blog.Theme'),
        ),
    ]
