# Generated by Django 3.0.7 on 2020-06-22 17:12

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20200602_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='currency',
            field=djmoney.models.fields.CurrencyField(blank=True, default='XYZ', help_text='default currency for the country', max_length=3, null=True),
        ),
        migrations.DeleteModel(
            name='Currency',
        ),
    ]
