# Generated by Django 3.0.7 on 2020-07-14 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_auto_20200710_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='backup_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='document',
            name='original_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='image',
            name='backup_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='image',
            name='original_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
