# Generated by Django 3.0.7 on 2020-07-21 12:51

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_auto_20200714_0809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='meta_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='meta_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
    ]
