# Generated by Django 3.0.6 on 2020-06-03 09:40

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20200602_1634'),
        ('shop', '0002_auto_20200603_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalitem',
            name='is_addon',
            field=models.BooleanField(default=True, help_text='can be topping or extra for addon another item'),
        ),
        migrations.AddField(
            model_name='historicalitem',
            name='show_on_menu',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='item',
            name='is_addon',
            field=models.BooleanField(default=True, help_text='can be topping or extra for addon another item'),
        ),
        migrations.AddField(
            model_name='item',
            name='items_for_addon',
            field=models.ManyToManyField(blank=True, related_name='addon_items', to='shop.Item'),
        ),
        migrations.AddField(
            model_name='item',
            name='show_on_menu',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='historicalitem',
            name='unavailable_periods',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('bf', 'breakfast'), ('ln', 'lunch'), ('dn', 'dinner'), ('br', 'brunch')], max_length=4), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='historicalmenu',
            name='footer_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='historicalmenu',
            name='header_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='alt_images',
            field=models.ManyToManyField(blank=True, related_name='items_as_alt_image', to='common.Image'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item', to='common.Image'),
        ),
        migrations.AlterField(
            model_name='item',
            name='notes',
            field=models.ManyToManyField(blank=True, to='common.Note'),
        ),
        migrations.AlterField(
            model_name='item',
            name='unavailable_periods',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('bf', 'breakfast'), ('ln', 'lunch'), ('dn', 'dinner'), ('br', 'brunch')], max_length=4), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='menu',
            name='footer_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='menu',
            name='header_text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
