# Generated by Django 3.0.6 on 2020-06-03 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20200603_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalitem',
            name='show_on_menu_position',
            field=models.PositiveIntegerField(blank=True, help_text='position within menu section when menu sections have positions', null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='show_on_menu_position',
            field=models.PositiveIntegerField(blank=True, help_text='position within menu section when menu sections have positions', null=True),
        ),
        migrations.AddField(
            model_name='menusection',
            name='show_on_menu_position',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalitem',
            name='is_addon',
            field=models.BooleanField(default=False, help_text='can be topping or extra for addon another item'),
        ),
        migrations.AlterField(
            model_name='item',
            name='is_addon',
            field=models.BooleanField(default=False, help_text='can be topping or extra for addon another item'),
        ),
        migrations.AlterField(
            model_name='item',
            name='items_for_addon',
            field=models.ManyToManyField(blank=True, help_text='other items this can be added onto', related_name='addon_items', to='shop.Item'),
        ),
    ]
