# Generated by Django 3.0.6 on 2020-06-03 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20200603_0959'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalitem',
            old_name='show_on_menu_position',
            new_name='display_on_menu_position',
        ),
        migrations.RenameField(
            model_name='historicalitem',
            old_name='show_on_menu',
            new_name='is_display_on_menu',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='show_on_menu_position',
            new_name='display_on_menu_position',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='show_on_menu',
            new_name='is_display_on_menu',
        ),
        migrations.RemoveField(
            model_name='menusection',
            name='show_on_menu_position',
        ),
        migrations.DeleteModel(
            name='CustomMenuSection',
        ),
    ]
