# Generated by Django 3.0.6 on 2020-06-03 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20200603_1012'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MenuSection',
            new_name='MenuCategory',
        ),
        migrations.RemoveField(
            model_name='historicalitem',
            name='menu_section',
        ),
        migrations.RemoveField(
            model_name='item',
            name='menu_section',
        ),
    ]
