# Generated by Django 3.0.6 on 2020-06-03 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20200603_1014'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('is_display_on_menu', models.BooleanField(default=True)),
                ('display_on_menu_position', models.PositiveIntegerField(blank=True, null=True)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_sections', to='shop.Menu')),
                ('menu_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='menu_sections', to='shop.MenuCategory')),
            ],
        ),
        migrations.AddField(
            model_name='historicalitem',
            name='menu_section',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='shop.MenuSection'),
        ),
        migrations.AddField(
            model_name='item',
            name='menu_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='shop.MenuSection'),
        ),
    ]
