# Generated by Django 3.0.6 on 2020-06-03 10:44

from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20200603_1015'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menucategory',
            options={'verbose_name_plural': 'Menu Categories'},
        ),
        migrations.AlterModelOptions(
            name='menusection',
            options={'verbose_name_plural': 'Menu Sections'},
        ),
        migrations.AddField(
            model_name='historicalitem',
            name='addon_price',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='THB', help_text='price when addon another item', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='historicalitem',
            name='addon_price_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('THB', 'Baht')], default='THB', editable=False, max_length=3),
        ),
        migrations.AddField(
            model_name='historicalitem',
            name='is_option',
            field=models.BooleanField(default=False, help_text='can be a required option for another item (eg. meat in wrap)'),
        ),
        migrations.AddField(
            model_name='historicalitem',
            name='option_price',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='THB', help_text='price when option on another item', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='historicalitem',
            name='option_price_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('THB', 'Baht')], default='THB', editable=False, max_length=3),
        ),
        migrations.AddField(
            model_name='item',
            name='addon_price',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='THB', help_text='price when addon another item', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='addon_price_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('THB', 'Baht')], default='THB', editable=False, max_length=3),
        ),
        migrations.AddField(
            model_name='item',
            name='is_option',
            field=models.BooleanField(default=False, help_text='can be a required option for another item (eg. meat in wrap)'),
        ),
        migrations.AddField(
            model_name='item',
            name='items_for_option',
            field=models.ManyToManyField(blank=True, help_text='item(s) this can be an option on', related_name='option_items', to='shop.Item'),
        ),
        migrations.AddField(
            model_name='item',
            name='option_price',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='THB', help_text='price when option on another item', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='option_price_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('THB', 'Baht')], default='THB', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='historicalitem',
            name='is_addon',
            field=models.BooleanField(default=False, help_text='can be a topping or extra for addon another item (eg. ice cream sprinkles)'),
        ),
        migrations.AlterField(
            model_name='historicalitem',
            name='is_display_on_menu',
            field=models.BooleanField(default=True, help_text='can be ordered as standalone item'),
        ),
        migrations.AlterField(
            model_name='historicalitem',
            name='price',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='THB', help_text='standalone order price', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='is_addon',
            field=models.BooleanField(default=False, help_text='can be a topping or extra for addon another item (eg. ice cream sprinkles)'),
        ),
        migrations.AlterField(
            model_name='item',
            name='is_display_on_menu',
            field=models.BooleanField(default=True, help_text='can be ordered as standalone item'),
        ),
        migrations.AlterField(
            model_name='item',
            name='items_for_addon',
            field=models.ManyToManyField(blank=True, help_text='item(s) this can be added onto', related_name='addon_items', to='shop.Item'),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='THB', help_text='standalone order price', max_digits=8, null=True),
        ),
    ]
