# Generated by Django 3.0.7 on 2020-06-16 08:55

from django.db import migrations
import fontawesome_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_auto_20200615_1343'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addongroup',
            options={'verbose_name_plural': 'Addon Groups'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ('display_on_menu_position',)},
        ),
        migrations.AlterModelOptions(
            name='itemaddongroupmemberships',
            options={'verbose_name_plural': 'Item Addon Group Memberships'},
        ),
        migrations.AlterModelOptions(
            name='itemaddongroups',
            options={'verbose_name_plural': 'Item Addon Groups'},
        ),
        migrations.AlterModelOptions(
            name='menusection',
            options={'ordering': ('display_on_menu_position',), 'verbose_name_plural': 'Menu Sections'},
        ),
        migrations.AddField(
            model_name='menucategory',
            name='icon',
            field=fontawesome_5.fields.IconField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='menusection',
            name='custom_icon',
            field=fontawesome_5.fields.IconField(blank=True, max_length=60),
        ),
    ]
