# Generated by Django 3.0.7 on 2020-06-16 12:24

import django.contrib.postgres.fields
from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_auto_20200616_0855'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemaddongroupmemberships',
            old_name='addon_price_currency',
            new_name='custom_addon_price_currency',
        ),
        migrations.RenameField(
            model_name='itemaddongroups',
            old_name='standard_price_currency',
            new_name='per_addon_price_currency',
        ),
        migrations.RemoveField(
            model_name='itemaddongroupmemberships',
            name='addon_price',
        ),
        migrations.RemoveField(
            model_name='itemaddongroups',
            name='standard_price',
        ),
        migrations.AddField(
            model_name='itemaddongroupmemberships',
            name='custom_addon_price',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='THB', help_text='set custom price to override default addon price, set to 0 to be Free', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='itemaddongroups',
            name='per_addon_price',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='THB', help_text='default price for each extra addon in this group (eg. toppings are $1 extra each)', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='historicalitem',
            name='unavailable_periods',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('bf', 'breakfast'), ('ln', 'lunch'), ('dn', 'dinner'), ('br', 'brunch')], max_length=4), blank=True, default=list, help_text="list of period choices when unavailable (eg. ['bf','ln'] for breakfast, lunch)", size=None),
        ),
        migrations.AlterField(
            model_name='item',
            name='unavailable_periods',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('bf', 'breakfast'), ('ln', 'lunch'), ('dn', 'dinner'), ('br', 'brunch')], max_length=4), blank=True, default=list, help_text="list of period choices when unavailable (eg. ['bf','ln'] for breakfast, lunch)", size=None),
        ),
    ]
