# Generated by Django 3.0.7 on 2020-06-17 06:37

from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_auto_20200616_1224'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemaddongroups',
            old_name='addon_free_count',
            new_name='custom_addon_free_count',
        ),
        migrations.RenameField(
            model_name='itemaddongroups',
            old_name='addon_max_count',
            new_name='custom_addon_max_count',
        ),
        migrations.RenameField(
            model_name='itemaddongroups',
            old_name='per_addon_price',
            new_name='custom_per_addon_price',
        ),
        migrations.RenameField(
            model_name='itemaddongroups',
            old_name='per_addon_price_currency',
            new_name='custom_per_addon_price_currency',
        ),
        migrations.AddField(
            model_name='addongroup',
            name='addon_free_count',
            field=models.SmallIntegerField(blank=True, help_text='number of free addons allowed (eg. 1 for salad dressing)', null=True),
        ),
        migrations.AddField(
            model_name='addongroup',
            name='addon_max_count',
            field=models.SmallIntegerField(blank=True, help_text='maxiumum number of addons allowed (eg. 10 salad toppings)', null=True),
        ),
        migrations.AddField(
            model_name='addongroup',
            name='per_addon_price',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='THB', help_text='default price for each extra addon in this group (eg. toppings are $1 extra each)', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='addongroup',
            name='per_addon_price_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('THB', 'Baht')], default='THB', editable=False, max_length=3),
        ),
    ]
