# Generated by Django 3.0.7 on 2020-06-22 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('line_app', '0001_initial'),
        ('shop', '0015_auto_20200617_0637'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalshop',
            name='line_channel',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='line_app.LineChannel'),
        ),
        migrations.AddField(
            model_name='shop',
            name='line_channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='line_app.LineChannel'),
        ),
    ]
