# Generated by Django 3.0.7 on 2020-07-10 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_auto_20200625_1424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalshop',
            name='line_channel',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='line_channel',
        ),
    ]
