# Generated by Django 3.0.7 on 2020-07-10 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_auto_20200622_1712'),
        ('shop', '0018_auto_20200710_0836'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='gramables',
            field=models.ManyToManyField(to='common.Image'),
        ),
    ]
