# Generated by Django 3.0.7 on 2020-07-18 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_auto_20200714_0809'),
        ('shop', '0020_auto_20200715_0856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='gramables',
            field=models.ManyToManyField(blank=True, to='common.Image'),
        ),
    ]
