# Generated by Django 3.0.7 on 2020-07-20 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_auto_20200720_0609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalmenu',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalmenu',
            name='shop',
        ),
        migrations.RemoveField(
            model_name='historicalshop',
            name='address',
        ),
        migrations.RemoveField(
            model_name='historicalshop',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalshop',
            name='icon_image',
        ),
        migrations.RemoveField(
            model_name='historicalshop',
            name='logo_image',
        ),
        migrations.RemoveField(
            model_name='historicalshop',
            name='owner',
        ),
        migrations.DeleteModel(
            name='HistoricalItem',
        ),
        migrations.DeleteModel(
            name='HistoricalMenu',
        ),
        migrations.DeleteModel(
            name='HistoricalShop',
        ),
    ]
