# Generated by Django 3.0.7 on 2020-07-21 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('line_app', '0019_auto_20200720_1421'),
        ('shop', '0024_auto_20200721_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='line_channel_membership',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='line_app.LineChannelMembership'),
        ),
    ]
