# Generated by Django 3.0.7 on 2020-07-21 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_auto_20200721_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='addon_items',
            field=models.ManyToManyField(related_name='order_items_as_addon', to='shop.Item'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='option_items',
            field=models.ManyToManyField(related_name='order_items_as_option', to='shop.Item'),
        ),
    ]
