# Generated by Django 3.0.7 on 2020-07-22 06:11

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_auto_20200721_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='draft_cart',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
    ]
