# Generated by Django 3.0.7 on 2020-08-04 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0028_auto_20200722_0707'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='current_status',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(None, 'no status'), (0, 'draft'), (1, 'order placed'), (2, 'customer cancelled'), (3, 'shop rejected'), (4, 'shop confirmed'), (5, 'shop complete'), (6, 'expired or abandoned')], default=0, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='next_status',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(None, 'no status'), (0, 'draft'), (1, 'order placed'), (2, 'customer cancelled'), (3, 'shop rejected'), (4, 'shop confirmed'), (5, 'shop complete'), (6, 'expired or abandoned')], default=1, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='previous_status',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(None, 'no status'), (0, 'draft'), (1, 'order placed'), (2, 'customer cancelled'), (3, 'shop rejected'), (4, 'shop confirmed'), (5, 'shop complete'), (6, 'expired or abandoned')], default=None, null=True),
        ),
    ]
