# Generated by Django 3.0.7 on 2020-08-12 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0030_auto_20200812_1401'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='pushover_user_identifier',
            new_name='pushover_user_key',
        ),
    ]
