# Generated by Django 3.0.6 on 2020-06-03 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20200602_1634'),
        ('communication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='attachments',
            field=models.ManyToManyField(blank=True, to='common.Upload'),
        ),
    ]
