# Generated by Django 2.1.2 on 2019-04-06 20:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('trello', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('trello_id', models.CharField(max_length=24)),
                ('trello_url', models.URLField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('color', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='board',
            name='trello_shortlink',
        ),
        migrations.RemoveField(
            model_name='card',
            name='trello_shortlink',
        ),
        migrations.RemoveField(
            model_name='list',
            name='trello_shortlink',
        ),
        migrations.AddField(
            model_name='board',
            name='trello_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='trello_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='list',
            name='trello_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='card',
            name='labels',
        ),
        migrations.AddField(
            model_name='label',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='trello.Board'),
        ),
        migrations.AddField(
            model_name='card',
            name='labels',
            field=models.ManyToManyField(related_name='cards', to='trello.Label'),
        ),
    ]
