# Generated by Django 2.1.2 on 2019-04-06 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trello', '0002_auto_20190406_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='position',
            field=models.FloatField(),
        ),
    ]
