# Generated by Django 2.1.2 on 2019-04-06 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trello', '0003_auto_20190406_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
    ]
