# Generated by Django 2.1.7 on 2019-04-20 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trello', '0004_card_is_closed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='trello_id',
            field=models.CharField(max_length=24, unique=True),
        ),
        migrations.AlterField(
            model_name='board',
            name='trello_url',
            field=models.URLField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='trello_id',
            field=models.CharField(max_length=24, unique=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='trello_url',
            field=models.URLField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='label',
            name='trello_id',
            field=models.CharField(max_length=24, unique=True),
        ),
        migrations.AlterField(
            model_name='label',
            name='trello_url',
            field=models.URLField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='list',
            name='trello_id',
            field=models.CharField(max_length=24, unique=True),
        ),
        migrations.AlterField(
            model_name='list',
            name='trello_url',
            field=models.URLField(blank=True, null=True, unique=True),
        ),
    ]
